### ISSUE TITLE
Add tests 

### ISSUE THREAD

**Issue by ocramz** [gagandeepb/Frames-beam#9]
* Unit tests 

* DB integration tests on Travis
  - see https://github.com/fpco/odbc/blob/master/.travis.yml

**Comment by gagandeepb** [comment]
About unit tests: how can I set up a replicable database environment so anyone cloning the repo is able to run the unit tests which will depend on a particular db name with certain table(s)/data in it ?

Similar question for Travis: is it possible to set up a database with a particular schema, filled with some mock data that Travis can use to run some tests against?

**Comment by gagandeepb** [comment]
Done. Integration tests added.
